# Generated by Django 2.0.7 on 2018-07-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20180727_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
    ]
