# Generated by Django 2.0.7 on 2018-07-25 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='non_member_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='m_friends',
            field=models.ManyToManyField(related_name='befriended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='nm_friends',
            field=models.ManyToManyField(related_name='m_befriended', to='accounts.non_member_user'),
        ),
    ]
