# Generated by Django 2.0.7 on 2018-07-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180725_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nm_friends',
            field=models.ManyToManyField(related_name='befriended', to='accounts.non_member_user'),
        ),
    ]
