# Generated by Django 2.0.7 on 2018-07-27 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180727_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='befriended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, null=True, related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nm_friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='befriended', to='accounts.non_member_user'),
        ),
    ]
