# Generated by Django 2.0.7 on 2018-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180730_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='matches',
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_messages',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
