# Generated by Django 2.0.7 on 2018-07-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180730_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pending_messages',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
